version: '3'

services:
  django:
    build:
      context: .
    image: django-redis-docker
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - mynetwork

  redis:
    image: "redis:latest"
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
